parameters:
    seo.defaults:
        author: 'Agentur Erlich'
        robots: 'index, follow'
        revisitAfter: ''
        keywords: ''
        description: ''
        url: ''
        siteName: ''
        title: 'Erlich Fliesen'
        image: 'media/favicon/erlich-fliesen-favicon.svg'
        imgAlt: 'Erlich Fliesen Logo'
        lang: 'de'
