#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a Gitea Actions repo secret via `tea api`
# (Gitea, not GitHub, backs this repo's tracker — see docs/agents/issue-tracker.md).
# The secrets endpoint is PUT-only (upsert). Falls back to a warning if tea
# is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v tea >/dev/null 2>&1; then
    if tea api "/repos/{owner}/{repo}/actions/secrets/${name}" -X PUT -f data="$value" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s Gitea secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("Gitea secret $name (set it manually: tea api /repos/{owner}/{repo}/actions/secrets/$name -X PUT -f data=...)")
  warn "skipped Gitea secret $name — tea not ready; set it later"
}

# set_var NAME VALUE — set a Gitea Actions repo variable (non-secret). Gitea's
# variables endpoint is POST-to-create / PUT-to-update; try POST first (fresh
# repo, nothing set yet) and fall back to PUT so re-runs stay idempotent.
set_var() {
  local name="$1" value="$2"
  if command -v tea >/dev/null 2>&1; then
    if tea api "/repos/{owner}/{repo}/actions/variables/${name}" -X POST -f value="$value" >/dev/null 2>&1 \
      || tea api "/repos/{owner}/{repo}/actions/variables/${name}" -X PUT -f value="$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s Gitea variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("Gitea variable $name")
  warn "skipped Gitea variable $name — tea not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "FliesenErlich — provision staging/prod deploy"

# ── Stage 1: SSH deploy user + key ─────────────────────────────────────────
stage "VPS — SSH deploy user & key"
say "The Gitea Actions workflow deploys via SCP+SSH, mirroring CodersPlacePI."
say "You need a deploy user on the VPS and its private key on this machine."
step "On the VPS, confirm (or create) a deploy user, e.g.: adduser deploy"
step "Generate a dedicated keypair if one doesn't exist: ssh-keygen -t ed25519 -f ~/.ssh/fliesenerlich_deploy -N ''"
step "Append the .pub half to the deploy user's ~/.ssh/authorized_keys on the VPS."
step "Confirm it works: ssh -i ~/.ssh/fliesenerlich_deploy <user>@<host> whoami"
ask SSH_HOST "VPS hostname or IP:"
ask SSH_USER "Deploy username on the VPS:"
say "Now paste the PRIVATE key contents (the file you generated above)."
ask_secret SSH_PRIVATE_KEY "Paste the private key (whole file, incl. BEGIN/END lines):"
write_env SSH_HOST "$SSH_HOST"
write_env SSH_USER "$SSH_USER"

# ── Stage 2: deploy directory paths ────────────────────────────────────────
stage "VPS — staging & prod deploy paths"
say "The workflow rm -rf's the target dir's contents then untars the build into it —"
warn "make sure these paths point at empty/dedicated web roots, never a home dir or shared path."
step "Confirm (or create) the prod web root on the VPS, e.g.: mkdir -p /var/www/fliesenerlich"
step "Confirm (or create) the staging web root on the VPS, e.g.: mkdir -p /var/www/fliesenerlich-staging"
ask PROD_DEPLOY_PATH "Absolute prod deploy path on the VPS:"
ask STAGING_DEPLOY_PATH "Absolute staging deploy path on the VPS:"
write_env PROD_DEPLOY_PATH "$PROD_DEPLOY_PATH"
write_env STAGING_DEPLOY_PATH "$STAGING_DEPLOY_PATH"

# ── Stage 3: public URLs ───────────────────────────────────────────────────
stage "Public URLs"
say "These feed astro.config.mjs's site option (sitemap/canonical URLs) at build time."
ask PROD_URL "Prod site URL (e.g. https://erlich-fliesen.de):"
ask STAGING_URL "Staging site URL (e.g. https://staging.erlich-fliesen.de):"
write_env PROD_URL "$PROD_URL"
write_env STAGING_URL "$STAGING_URL"

# ── Stage 4: write Gitea repo secrets + vars ───────────────────────────────
stage "Gitea — repo secrets & variables"
say "Writing everything captured so far to git.arthurerlich.de's FliesenErlich repo"
say "via tea api (Settings → Actions → Secrets/Variables is the manual fallback)."
set_secret SSH_PRIVATE_KEY "$SSH_PRIVATE_KEY"
set_secret SSH_HOST "$SSH_HOST"
set_secret SSH_USER "$SSH_USER"
set_var PROD_URL "$PROD_URL"
set_var STAGING_URL "$STAGING_URL"
set_var PROD_DEPLOY_PATH "$PROD_DEPLOY_PATH"
set_var STAGING_DEPLOY_PATH "$STAGING_DEPLOY_PATH"

# ── Stage 5: test deploy from both branches ────────────────────────────────
stage "Test deploy — main & staging"
say ".gitea/workflows/deploy.yml is already adapted for this repo and triggers on"
say "pushes to main and staging."
step "Push a trivial commit to staging and watch the Actions run in Gitea's UI."
open_url "https://git.arthurerlich.de/haylan/FliesenErlich/actions"
confirm "Did the staging deploy job succeed and land on \$STAGING_DEPLOY_PATH?" \
  || warn "fix staging before touching main — check the deploy job logs"
step "Push a trivial commit to main and watch the Actions run."
confirm "Did the main (prod) deploy job succeed and land on \$PROD_DEPLOY_PATH?" \
  || warn "prod deploy needs another pass before this ticket can close"
# ──────────────────────────────────────────────────────────────────────────

finish
